# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='imgUrl',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(max_length=100),
        ),
    ]
