# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_emailcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcontact',
            old_name='customerEmail',
            new_name='customer_email',
        ),
    ]
