# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160526_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontact',
            name='title',
            field=models.CharField(default='old contact', max_length=254),
            preserve_default=False,
        ),
    ]
