# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_emailcontact_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcontact',
            name='title',
        ),
    ]
