# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160508_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Page')),
                ('headline', models.CharField(max_length=100)),
                ('body_text', models.TextField()),
            ],
            bases=('website.page',),
        ),
        migrations.AlterField(
            model_name='projects',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.ProjectPage'),
        ),
    ]
