# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160529_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='imgUrl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
