# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160516_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='newpage',
            field=models.OneToOneField(default=datetime.datetime(2016, 5, 16, 16, 49, 42, 564859, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='website.ProjectPage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.Page'),
        ),
    ]
