# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160516_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='page',
        ),
    ]
