# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_projects_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='newpage',
        ),
    ]
