# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160608_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=420, null=True),
        ),
    ]
