# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_projects_newpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ProjectPage',
        ),
    ]
