# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160516_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.Page'),
            preserve_default=False,
        ),
    ]
